/* =====================================================
   Core domain types for the Ad Reporting App
   ===================================================== */

export type Channel = 'meta' | 'google' | 'tiktok';
export type UserRole = 'admin' | 'client' | 'super_admin';

/* ----- SaaS / Licencias ----- */
export type PlanId = 'starter' | 'pro' | 'enterprise';
export type LicenseStatus = 'active' | 'suspended' | 'expired' | 'trial';

export interface Plan {
  id: PlanId;
  name: string;
  price_monthly: number;
  max_clients: number | null; // null = ilimitado
  max_channels: number;
  features: string[];
  color: string;
}

export interface LicenseAddons {
  story_engine?: boolean;
}

export interface License {
  id: string;
  agency_id: string;
  agency_name: string;
  agency_email: string;
  plan_id: PlanId;
  status: LicenseStatus;
  created_at: string;
  expires_at: string | null;
  activated_at: string | null;
  notes: string | null;
  clients_count: number;
  temp_password: string | null;
  addons: LicenseAddons;
}

/* ----- Auth ----- */
export interface AppUser {
  id: string;
  email: string;
  role: UserRole;
  full_name: string | null;
  avatar_url: string | null;
}

/* ----- Client ----- */
export interface Client {
  id: string;
  name: string;
  slug: string;
  logo_url: string | null;
  timezone: string;
  is_active: boolean;
  created_at: string;
  channels?: Channel[];
  sync_status?: Record<Channel, 'idle' | 'syncing' | 'success' | 'error'>;
}

/* ----- Metric definitions ----- */
export type MetricUnit = 'currency' | 'percent' | 'integer' | 'decimal' | 'ratio';

export interface MetricDefinition {
  key: string;
  label: string;
  description?: string;
  unit: MetricUnit;
  channels: Channel[];
  is_derived: boolean;
  formula?: string;
}

export interface MetricConfig {
  metric_key: string;
  label: string;
  unit: MetricUnit;
  is_visible: boolean;
  display_order: number;
  show_in_kpi: boolean;
  show_in_table: boolean;
  show_in_chart: boolean;
}

/* ----- Credentials ----- */
export interface ChannelCredential {
  id: string;
  client_id: string;
  channel: Channel;
  is_active: boolean;
  last_synced_at: string | null;
  sync_status: 'idle' | 'syncing' | 'success' | 'error' | null;
  sync_error: string | null;
}

/* ----- Report data ----- */
export interface MetricTotals {
  impressions: number;
  clicks: number;
  spend: number;
  conversions: number;
  conversions_value: number;
  reach: number;
  video_views: number;
  ctr: number;
  cpc: number;
  cpm: number;
  roas: number;
  cvr: number;
  cpa: number;
  [key: string]: number;
}

export interface DailyDataPoint {
  date: string;
  dayIndex?: number;
  impressions?: number;
  clicks?: number;
  spend?: number;
  conversions?: number;
  conversions_value?: number;
  reach?: number;
  video_views?: number;
  ctr?: number;
  cpc?: number;
  cpm?: number;
  roas?: number;
  cvr?: number;
  cpa?: number;
}

export interface CampaignSummary {
  id: string;
  name: string;
  channel: Channel;
  status: string;
  external_id: string;
  objective?: string | null;
  impressions?: number;
  clicks?: number;
  spend?: number;
  conversions?: number;
  conversions_value?: number;
  reach?: number;
  video_views?: number;
  link_clicks?: number;
  ctr?: number;
  cpc?: number;
  cpm?: number;
  roas?: number;
  cvr?: number;
  cpa?: number;
}

export interface PeriodReport {
  totals: MetricTotals;
  byDate: DailyDataPoint[];
  byCampaign: CampaignSummary[];
}

export interface ReportResponse {
  primary: PeriodReport;
  comparison: PeriodReport | null;
  deltas: Record<string, { absolute: number; percent: number; direction: 'up' | 'down' | 'flat' }> | null;
  allowedMetrics: MetricConfig[];
  syncStatus: Partial<Record<Channel, 'idle' | 'syncing' | 'success' | 'error'>>;
}

/* ----- Client-facing reports (generated by admin) ----- */
export type ClientReportStatus = 'draft' | 'published';

export interface TopCreative {
  name: string;
  channel: Channel;
  spend: number;
  impressions: number;
  ctr: number;
  conversions: number;
  thumbnail_url?: string | null;
}

export interface SpendResult {
  channel: Channel;
  spend: number;
  conversions: number;
  cpa: number;
  roas: number;
}

export interface AudienceSegment {
  name: string;
  reach: number;
  engagement_rate: number;
  notes?: string;
}

export interface SocialGrowthMetric {
  platform: 'instagram' | 'facebook' | 'tiktok' | 'youtube' | 'linkedin' | 'x';
  followers_start: number;
  followers_end: number;
  growth_pct: number;
}

export interface ClientReport {
  id: string;
  client_id: string;
  title: string;
  period_start: string;   // ISO date
  period_end: string;
  status: ClientReportStatus;
  created_at: string;
  published_at: string | null;
  created_by: string | null;

  executive_summary: string;
  top_creatives: TopCreative[];
  spend_vs_results: SpendResult[];
  audiences: AudienceSegment[];
  social_growth: SocialGrowthMetric[];
  recommendations: string;
}

/* ----- Sync ----- */
export interface SyncLog {
  id: string;
  client_id: string;
  channel: Channel;
  started_at: string;
  finished_at: string | null;
  status: 'running' | 'success' | 'partial' | 'error';
  rows_upserted: number | null;
  error_detail: string | null;
}

/* ----- Agency Meta Connection ----- */
export interface AdAccount {
  id: string;          // e.g. "act_123456789"
  name: string;
  account_status: number; // 1 = ACTIVE
  currency: string;
}
